#!/bin/bash

############################################################
# Help                                                     #
############################################################
Help()
{
   # Display Help
   echo
   echo "An Update Script for Soulseek on Linux, utilizing the .AppImage Download-API provided by Soulseek"
   echo "Installs Soulseek directly from the source and manages updates"
   echo
   echo "Simply enter the command without any dashes and it'll update Soulseek"
   echo
   echo "Syntax: qslsk [ -g| -h| --help| -v]"
   echo
   echo "Options:"
   echo "    -h | --help    Print this Help."
   echo "    -v             Print software version and exit."
   echo "    -g             Print the GPL license notification."
   echo
}

Version()
{
   # Display Software Version
   echo
   echo -e "Version 1.0, \e[35mqandy inc.\e[0m (not a real company , though it sounds nice)"
   echo
}

License()
{
   cat /usr/share/qslsk/LICENSE
   echo
   echo
   echo "For a better view, visit:"
   echo "https://github.com/Qand7/qsoulseek/blob/main/LICENSE"
   echo
   echo
   echo
   echo "(It's just the GPL 3.0 license)"
}

############################################################
############################################################
# Main program                                             #
############################################################
############################################################
############################################################
############################################################
while getopts ":hvg-:" opt; do
   case $opt in
      h) # Display Help
         Help
         exit;;

      v) # Display Version
         Version
         exit;;

      g) # Display License
         License
         exit;;

     \?) # Invalid option
         echo "Error: Invalid option"
         exit;;

      -) # Long option
         case $OPTARG in

          help) # Display Help
                Help
                exit;;
                 
          *)    # Invalid Long option 
                echo "Error: Invalid option"
                exit;;

         esac;;
         
   esac
done

# Update
curl -L "https://soulseek.s3.us-west-2.amazonaws.com/SoulseekQt-2024-6-30.AppImage" -o ~/temp.AppImage
sudo mkdir /usr/share/soulseek
sudo cp ~/temp.AppImage /usr/share/soulseek/soulseekqt.AppImage
sudo chmod +x /usr/share/soulseek/soulseekqt.AppImage
rm ~/temp.AppImage

echo
echo "----------------"
echo "Update Complete"
